<?php
$lang['home'] 			= 'الصفحة الرئيسية';
$lang['register'] 		= 'تسجيل';
$lang['signin'] 		= 'تسجيل الدخول';
$lang['add_dubarah'] 			= 'أضافة دوبارة';
$lang['categories'] 	= 'المجموعات';
$lang['succ_dubarah'] 	= 'تمت اضافة الوظيفة بنجاح ';
$lang['succ_bus'] 	=	 'تمت اضافة العمل بنجاح';
$lang['category'] 	=	 'مجموعات الكورسات';
$lang['err_dubarah'] 	= 'هنالك مشكلة يرجى المحاولة مرة أخرى';
$lang['skills'] 		= 'الخبرات';
$lang['firstname'] 				= 'الاسم الاول';
$lang['last_name'] 				= 'الاسم الاخير';
$lang['email'] 					= 'الايميل';
$lang['password'] 				= 'كلمة السر';
$lang['country'] 				= 'الدولة';
$lang['search'] 				= 'بحث';
$lang['services'] 				=  'الخدمات';
$lang['city'] 					= 'المدينة / المقاطعة';
$lang['languages'] 				= 'اللغات';
$lang['gender'] 				= 'الجنس';
$lang['mobile'] 				= 'الموبايل';
$lang['title'] 					= 'المسمى الوظيفي';
$lang['employer'] 				= 'الجهة الموظفة';

$lang['add_business'] 			= 'أضافة أعمال';
$lang['address'] 				= 'المدينة/العنوان';
$lang['job_type'] 				= 'نوع الفرصة';
$lang['expiration'] 			= 'مدة الانتهاء';
$lang['subcategories'] 			= 'التصنيف الفرعي';
$lang['logo'] 					= 'أضف شعار الشركة';
$lang['how'] 					= 'كيف تريد استقبال طلبات التوظيف';
$lang['both'] 					= 'الأثنان';
$lang['apply_scss'] 			= ' شكراً لك، تم تقديم طلبك بنجاح. ستقوم الجهة الموظفة بالتواصل معك قريباً في حالة كانت خبرتك مطابقة لمتطلبات الوظيفة';
$lang['owner'] 					= '  لايمكن للمالك التقديم على الوظيفة  ';
$lang['img_up'] 				= 'تم تحميل الصورة بنجاح';
$lang['deadline'] 			=  'الاعلان صالح حتى';
$lang['choose'] 				= 'أختر';
$lang['home'] 					= 'الصفحة الرئيسية';
$lang['dubarah'] 				= 'دوبارة';
$lang[''] 						= '';
$lang['full_time'] 				= 'كل الوقت';
$lang['part_time'] 				= 'وقت جزئي';
$lang['req_skills'] 				= 'المهارات المطلوبة ';
$lang['job_up'] 					= 'أكمل معلوماتك';
$lang['your_note'] 					=  'أكتب رسالتلك';
$lang['upload_cv'] 					=  'قم بتحميل سيرتك الذاتية';
$lang['share'] 						=  'قم بمشاركة الدبارة';
$lang['need_log'] 					= 'يجب عليك تسجيل الدخول';
$lang['logout'] 					= 'تسجيل الخروج';
$lang['need_com'] 					= 'يجب عليك أكمال معلومات حسابك';
$lang['reg_updated'] 			= 'لقد تم تحديث معلوماتك الرئيسية';
$lang['not_reg_updated'] 			= 'لم يتم تحديث ';
$lang['social_media'] 			=  'سوشل ميديا';
$lang['done_reg'] 				=  ' تم !</h1><h3> سيصلك بريد الكتروني خلال دقيقتين لتفعيل حسابك</h3> ';
$lang['jobs_section'] 			=  'اعلانات العمل';
$lang['phone_apply'] 			=  'تقدم عن طريق الهاتف';
$lang['recent_jobs'] 			=  'احدث الوظائف';
$lang['most_viewed'] 			=  'الوظائف الاكثر مشاهدة';
$lang['apply_now'] 				= 'تقدم الأن';
$lang['resume'] 				= 'السيرة الذاتية';
$lang['jobs'] 					= 'الوظائف';
$lang['description'] 			= 'وصف العمل';
$lang['male'] 					= 'ذكر';
$lang['female'] 				= 'أنثى';
$lang['freelance'] 				= 'عمل مؤقت';
$lang['contract'] 				= 'عمل بدوام كامل';
$lang['code_sent'] 				= ' تم ارسال رسالة التفعيل الى ايميلك';
$lang['mail'] 					= 'ذكر';
$lang['female'] 				= 'أنثى';
$lang['user_com'] 				= 'لقدم تم تحديث معلوماتك بنجاح';
$lang['user_not_com'] 				= 'لم يتم تحديث معلوماتك ';
$lang['user_created'] 				=  'تم إنشاء المستخدم بنجاح';
$lang['we_link'] 					=  'شبكة عالمية تعمل على ابتكار وطرح أفضل الحلول’';
$lang['refugees'] 					=  'لمشاكل';
$lang['solution'] 					=  'اللاجئين والقادمين الجدد';
$lang['welcome'] 					=  'مرحباً بك في شبكة دوبارة';
$lang['job_span'] 					=  'سيتم الغاء نشر الفرصة آلياً عند انتهاء المدة التي ستقوم بتحديدها';
$lang['any'] 						=  'لايهم';
$lang['Job_Preferences'] 			=  'تفضيلات فرصة العمل';
$lang['Who_can'] 					=  'من يستطيع التقدم للفرصة؟';
$lang['re_requirement'] 			=  'المهارات المطلوبة';
$lang['Only'] 			=  'لن يستطيع أحد التقدم لهذه الوظيفة الا اذا حقق الشروط أدناه';
$lang['phone_span'] 			=  'رقم الهاتف سيظهر للمتقدم عند الضغط على زر التقديم للوظيفة';
$lang['email_span'] 			=  'Email will not appear for applicants, we’ll send the applications directly to your inbox.';
$lang['done_dubatah'] 		=  'تم ادخال المنشور بنجاح، وهو الآن ينتظر موافقة النشر.<br/>سوف نقوم بمراجعته ونشره خلال 24 ساعة.';
$lang['thank_you'] 			=  'شكرا لك';
$lang['lastname'] 			=  'الاسم الأخير';
$lang['my_information'] 			=  'معلوماتي';
$lang['profile'] 				=  'حسابي';
$lang['my_skills'] 				=  'خبرات';
$lang['password_con'] 			=  'تأكيد كلمة المرور';
$lang['fail'] 					=  'خطأ';
$lang['success'] 				=  'تم بنجاح';
$lang['pass_changed'] 			=  'تم تعديل كلمة المرور الخاصة بك بنجاح يمكنك الآن تسجيل الدخول';
$lang['pass_not_changed'] 		=  'لم يتم تعديل كلمة المرور, يرجى المحاولة لاحقا';
$lang['token_error'] 			=  'يوجد خطأ في الكود المرسل';
$lang['complete_profile'] 		=  'يجب عليك إكمال ادخال بينات حسابك أولا حتى تستطيع التنقل في صفحتك الشخصية';
$lang['resend_code'] 			=  'إرسال كود التفعيل مرة أخرى';
$lang['code_not_resent'] 		=  'لم يتم إرسال الكود، يرجى المحاولة لاحقاً';
$lang['no_reset_mail'] 			=  'لم تقم بإدخال إيميلك ليتم ارسال الكود عليه';
$lang['code_sent_email'] 		=  'تم إرسال الكود إلى ايميلك يرجى النقر على الرابط في الايميل ليتم تغيير كلمة المرور';
$lang['code_not_sent_email'] 	=  'حدث خطأ أثناء ارسال الايميل، يرجى المحاولة لاحقاً';
$lang['forgetten'] 				=  'نسيت';
$lang['ur_pass'] 				=  'كلمة المرور الخاصة بك؟';
$lang['enter_reset_email'] 		=  'أدخل ايميلك ليتم إرسال كود التفعيل لتستطيع تغيير كلمة السر الخاصة بك';
$lang['err_user'] 				=  'الإيميل المدخل غير موجود';
$lang['send_code'] 				=  'إرسال الكود';
$lang['update_info'] 			=  'حدث معلوماتك';
$lang['needlogin'] 				=  'يجب عليك ان تسجل الدخول كي تقدم على الوظيفة';
$lang['aboutus'] 				=  'حول دوبارة ';
$lang['vision'] 				=  'الرؤية والمهمة';
$lang['team'] 					=  'الفريق';
$lang['full_name'] 					=  'الأسم الكامل';
$lang['all_dubarahs'] 					=  'مجموع الدوباراة';
$lang['download_cv'] 					=  'تحميل السيرة الذانية';
$lang['user_photo'] 			= 'صورتك';
$lang['about_dubarah'] 					=  ' منظمة كندية مسجلة ضمن مقاطعة أونتاريو تعمل منذ سنة 2013 علي دمج خبرات الاجئين ومهاراتهم بمشاكل المجتمعات الـتي اتخـذوهـا كـوطـن جـديـد لـهم. تـعد دوبـارة “شـبكة تـطوع نـوعـية” بـكونـها تـقوم عـلى الاسـتفادة مـن خـبرات الـلاجـىء نـفسه وتـسخيرهـا لحـل مـشاكـل الـسوريـين والـمجتمع مـن حـولـه، والـتي بـدورهـا أثـبتت فـعالـيتها بـمساعـدة مـايـزيـد عـن 3 مـليون لاجـىء 
سوري ضمن 15 دولة، بقدرة تطوعية وصل عدد افرادها لـ 180 الف. 
';
$lang['ahmad'] 			=  '<h3 style="color:black;text-align: right;">أحمد إدلبي</h3> <br/> <p '.(LANG()=='ar' ? 'style="text-align: right;"' : '').'>
  
مؤسس شبكة دوبارة, رئيس مجلس الإدارة والرئيس التنفيذي لدوبارة, والتي قام بتأسيسها في عام 2013 
أحمد مسؤول عن تحديد التوجيهات العامة واستراتيجيات المنتجات للشركة. هو يقود تصميم خدمات دوبارة وتطوير تقنياتها الأساسية والبنية التحتية.
</p>';
$lang['majd'] 			=  '<h3 style="color:black;text-align: right;">مجد خانجي </h3> <br/><p '.(LANG()=='ar' ? 'style="text-align: right;"' : '').'> 
الشريك المؤسس لشبكة دوبارة, مدير العمليات  
مجد هو مدير العمليات في دوبارة, يشرف على العمليات التجارية الخاصة بالمؤسسة  
قبل إنضمامه لدوبارة, عمل مجد كمسؤول عن الشركات وكبار العملاء لقسم المبيعات في شركة سيريتل للإتصالات السلكية واللاسلكية  
</p>';
$lang['talin'] 			=  '<h3 style="color:black;text-align: right;">تالين كديكيان  </h3> <br/> <p style="text-align: right;">
 
مديرة خدمات شبكة دوبارة  
تقود تالين إدارة خدمات دوبارة, التصميم, وعمليات التسويق عالمياً. 
هي المسؤولة عن الخدمات والمزايا الأساسية التي تشكل التجربة الاجتماعية لمستخدمي دوبارة  شهرياً.  
انضمت تالين لدوبارة في 2013 كمنسق مهام وساهمت في بناء الإصدارات الأولية لمزايا دوبارة الأساسية, ومن ضمنها إسأل دوبرجي.  
تلى ذلك تعيين تالين كمديرة خدمات الشبكة , حيث ضبطت النمط الخاص بثقافة دوبارة وقادت تطوير مهامها, قيمها واستراتيجيات الأفراد الخاصة بها. 
تالين حاصلة على اجازة في المعلوماتية والتطبيقات الادارية من الجامعة الافتراضية السورية  
</p>';
$lang['vision_def'] 			=  'تقوم شبكة دوبارة بدعم كل مايساهم بتحقيق منفعة ايجابية وشرعية للأفراد حول العالم، لضمان حصولهم على فرص عادلة ومميزة ترفع من سوية حياتهم، من خلال منصة الكترونية توفر امكانية تقديم ومشاركة المنافع والحلول بين مستخدمين الشبكة.';
$lang['about_us'] 				=  'حول دوبارة';
$lang['quick'] 					=  'روابط مهمة';
$lang['my_profile'] 			=  'حسابي';
$lang['not_skill'] 				=  'ليست من خبراتك';
$lang['my_dubarahs'] 			=  'دوباراتي';
$lang['how_apply'] 				=  'من تقدم';
$lang['see_post'] 				=  'مشاهدة';
$lang['who_applyed'] 			=  'المتقدمين';
$lang['email_apply'] 			=  'تقدم عبر الايميل';
$lang['total_dubarah'] 			=  'عدد الناس التي تمت مساعدتهم من عام 2013 حتى الأن';
$lang['with_inf'] 				=  'بمعلوماتك ';
$lang['join'] 					=  'انضمّ إلى دوبارة';
$lang['forgot_password'] 		=  'نسيت كلمة السر';
$lang['sign_up'] 				=  'تسجيل';
$lang['login'] 					=  'تسجيل الدخول';
$lang['login_user'] 			=  'تسجيل الدخول';
$lang['create_new'] 			=  'أنشاء حساب جديد';
$lang['privacy_policy'] 			=  "الخصوصية";

$lang['privacy'] 			=  "© Dubarah
Privacy policy
Latest update Feb 22th, 2017
Preamble
www.Dubarah.com (the “Website” “Dubarah”) is owned and operated by Dubarah Inc. and is a subscription based service that allows users to post services in regards to a variety of tasks, skills and any needs. The creator of an account in Dubarah is the User. We collect information about the User and any members that he or she invites to join the Dubarah. 
We are committed to providing all our Users with exceptional service. As providing this service involves the collection, use, storage and disclosure of some personal information about you (our User), protecting your personal information is one of our highest priorities.
We will inform you of why and how we collect, use and disclose your personal information, and obtain your consent where required.
This Privacy Policy outlines the principles and practices we will follow in protecting your personal information. Our privacy commitment includes ensuring the accuracy, confidentiality, and security of your personal information and allowing you to request access to, and correction of, your personal information.
Please contact us at: website@dubarah.com if you have any questions regarding our privacy policy or practices, or require any additional information on any of the below topics.
This Policy applies to all sites, mobile applications, and other online services (collectively, Platform) made available by Dubarah. It does not apply to other websites to which we link. You agree that your use of the Website signifies your assent to this Privacy Policy. If you do not agree with this Privacy Policy, please do not use the Website.
Undefined capitalized terms used herein shall have the definitions as set forth in our Terms of Use. By accessing or using the Platform, you agree to this Policy. IF YOU DO NOT AGREE TO THIS POLICY, PLEASE DO NOT ACCESS OR USE THE PLATFORM.
KEY TERMS
Please review the Key Terms section in the Terms of Use.
1) HOW YOU PROVIDE YOUR CONSENT
We will obtain your consent to collect, use or disclose personal information (except where, as noted below, we are authorized to do so without consent). 
You can provide your consent electronically or it can be implied where the purpose for collecting, using or disclosing the personal information would be considered obvious and you voluntarily provide personal information for that purpose. Examples of this are when you post files to your account. We support audio files, embedded Video for YouTube or Vimeo, PDF’s, Office documents and photos. Please note that any member who has account access can view or download those files.
Consent may also be implied where you are given notice of your personal information being used for mail-outs, the marketing of new services or products, fundraising, and you do not opt-out. 
Subject to certain exceptions (listed below), you can withhold or withdraw your consent for MyBand.IO to use your personal information in certain ways. Your decision to withhold or withdraw your consent to certain uses of personal information may restrict our ability to provide a particular service or product. If so, we will explain the situation to assist you in making a decision. 
There are special circumstances where we may collect, use or disclose some of your personal information without your knowledge or consent, when we are permitted or required by law. A full listing of such circumstances can be found in section 7 (Collection without knowledge or consent) of the Personal Information Protection and Electronic Documents Act, S.C. 2000, c. 5 [“PIPEDA”]. 
2) INFORMATION WE COLLECT
How we collect and store information depends on how you access and use the Platform. 
We collect two types of information from you: i) information that you voluntarily provide to us (e.g. through a voluntary registration process, sign-ups or emails); and ii) information that is collected automatically when using the Site (e.g. tracking cookies): 
Information You Provide Directly to Us
In order to fully access this Site, you must first complete the registration process, during which we will collect personal information about you, such as:
When you register for an Account;
When you participate in polls or surveys;
When you enroll for electronic newsletters;
When you request a quote or other information;
When you submit a quote;
When you make a purchase;
When you fill out any forms;
When you enter a sweepstakes or contest, or register for a promotion;
When you transmit User Content;
When you download or use one of our mobile applications; or
When you otherwise communicate with us or other users through the Platform.
This list is illustrative, not exhaustive; the Privacy Policy applies to all use of the Platform.
The information you provide directly to us may concern you or others and may include, but is not limited to: (a) name; (b) zip code; (c) email address; (d) home or business telephone number; (e) home, business or mailing address; (f) demographic information (e.g., gender, age, political preference, education, race or ethnic origin, and other information relevant to user surveys and/or offers); (g) date of birth; (h) insurance information; (i) photographs; (j) information about your project, request or need; (k) video or audio files; and/or (l) in certain circumstances, payment and/or identity verification information. It may also include information specific to services you are requesting or offering through the Platform, such as a business name, service description, qualifications and credentials. You are not required to provide us with such information, but certain features of the Platform may not be accessible or available, absent the provision of the requested information.
Information from Affiliates, Social Networking Sites, and other Non-affiliated Third Parties
We may collect information about you or others through Dubarah affiliates or through non-affiliated third parties. For example, you may be able to access the Platform through a social networking account, such as Facebook. If you access the Platform through your Facebook account, you may allow us to have access to certain information in your Facebook profile. This may include your name, profile picture, gender, networks, user IDs, list of friends, location, date of birth, email address, photos, videos, people you follow and/or who follow you, and/or your posts or “likes” and future information that could help us improve your experience on Dubarah website.
Social networking sites, such as Facebook, have their own policies for handling your information. For a description of how these sites may use and disclose your information including any information you make public, please consult the sites' privacy policies. We have no control over how any third-party site uses or discloses the personal information it collects about you.
We may also collect information about you or others through non-affiliated third parties. For example, to the extent permitted by law, we may, in our sole discretion, ask for and collect supplemental information from third parties, such as information about your credit from a credit bureau, or information to verify your identity or trustworthiness, or for other fraud or safety protection purposes. We may combine information that we collect from you through the Platform with information that we obtain from such third parties and information derived from any other products or services we provide.
Information That is Passively or Automatically Collected
Device/Usage Information. We and our third-party service providers, which include ad networks and analytics companies including Crashalytics, may use cookies, web beacons, and other tracking technologies to collect information about the computers or devices (including mobile devices) you use to access the Platform. As described further below, we may collect and analyze information including but not limited to (a) browser type; (b) ISP or operating system; (c) domain name; (d) access time; (e) referring or exit pages; (f) page views; (g) IP address; (h) unique device identifiers (e.g. IMIE); and (i) the type of device that you use. We may also track how frequently you access or use the Platform. We use this information (including the information collected by our third-party service providers) for Platform analytics (including to determine which portions of the Platform are used most frequently and what our users like/do not like), to assist in determining relevant advertising (both on and off the Platform), to evaluate the success of our advertising campaigns, and as otherwise described in this Policy.
Location Information. When you use the Platform, we may collect general location information (such as IP address). If you install our mobile app, we may ask you to grant us access to your mobile device's geolocation data. If you grant such permission, we may collect information about your precise geolocation, and we may use that information to improve the Platform, including providing you with location-based features (e.g. for identification of Services available near you). To deliver customized content and advertising, we may share your location information with our agents, vendors, or advertisers. If you access the Platform through a mobile device and you do not want your device to provide us with location-tracking information, you can disable the GPS or other location-tracking functions on your device, provided your device allows you to do this. See your device manufacturer's instructions for further details. If you disable certain functions, you may be unable to use certain parts of the Platform.
Cookies and Other Electronic Technologies. We and our third-party service providers may use cookies, clear GIFs, pixel tags, and other technologies that help us better understand user behaviour, personalize preferences, perform research and analytics, and improve the Platform. These technologies, for example, may allow us to tailor the Platform to your needs, save your password in password-protected areas, track the pages you visit, help us manage content, and compile statistics about Platform usage. We also use certain of these technologies to deliver advertisements through the Platform that may interest you. We or our third-party service providers also may use certain of these technologies in emails to our customers to help us track email response rates, identify when our emails are viewed, and track whether our emails are forwarded.
We may also use local shared objects (also known as Flash cookies) to assist in delivering special content, such as video clips or animation. Flash cookies are stored on your device, but they are not managed through your web browser. To learn more about how to manage Flash cookies, you can visit the Adobe website and make changes at the Global Privacy Settings Panel.
You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but your browser may allow you to modify your browser settings to decline cookies if you prefer. If you disable cookies, you may be prevented from taking full advantage of the Platform, because it may not function properly. Flash cookies operate differently than browser cookies, and cookie management tools available in a web browser may not affect flash cookies. As we adopt additional technologies, we may also gather additional information through other methods.
3) HOW DUBARAH USES THE INFORMATION WE COLLECT
Dubarah collects your data in order to enhance your use of the Website and its features, including without limitation for the purposes of: Conducting analytics; Contacting the User; Allowing content commenting; Providing customer service; Handling payments; Displaying content from external platforms; Managing email addresses and invitations; Helping us identify and/or provide information, products or services that may be of interest to you; and otherwise supporting your use of the Website.
The Personal Data used for the above purposes is elaborated on in this section of this document. 
We may use your information for any of the following reasons:
For the purposes for which you provided it; To enable you to use the services available through the Platform, including registering you for our services and verifying your identity and authority to use our services; For customer support and to respond to your inquiries;
For internal record-keeping purposes; To administer surveys, sweepstakes, promotions, or contests; To process billing and payment including sharing with third-party payment gateways and payment service providers in connection with the Platform; To improve and maintain the Platform and for product development; To address fraud or safety concerns, or to investigate complaints or suspected fraud or wrongdoing; To periodically send promotional emails regarding new products from Dubarah, special offers from Dubarah, or other information that may interest you; With your consent, to contact you by text message regarding certain services or information you have requested; With your consent, to contact you by telephone or text message regarding Platform features, improvements, or other products and services that may interest you; For Dubarah market research purposes, including, but not limited to, the customization of the Platform according to your interests; To contact you about goods and services that may interest you or with information about your use of the Platform; For other research and analytical purposes; and To resolve disputes, to protect ourselves and other users of the Platform, and to enforce any legal terms that govern your use of the Platform.
We may combine information that we collect from you through the Platform with information that we obtain from affiliated and nonaffiliated third parties, and information derived from any other products or services we provide.
We may aggregate and/or de-identify information collected through the Platform. We may use de-identified or aggregated data for any purpose, including without limitation for research and marketing purposes and may also share such data with any third parties, including without limitation, advertisers, promotional partners, sponsors, event promoters, and/or others.
4) WHEN DUBARAH DISCLOSES YOUR INFORMATION
At Dubarah, we are committed to ensuring the online privacy of our Users. Your Personal Information will not be sold or otherwise transferred to unaffiliated third parties without your approval. We will not disclose, use, or give any personal information to third parties for any purposes other than to our suppliers and other third parties who need to know the information in order to deliver services on our behalf.
Unless otherwise described in this Policy, we may also share the information that we collect from you through the Platform as follows:
Affiliates. We may share your information with any Dubarah affiliates, such as with our parent, subsidiaries, and divisions
Consent. We may disclose your information to nonaffiliated third parties based on your consent to do so. Such consent includes the disclosure of your information (a) in order to provide services or products that you have requested (please see below for more details); (b) when we have your permission; or (c) as described in this Policy, the Terms of Use, or any other legal terms governing your use of the Platform.
Informed Consent. You will receive notice when your personally identifiable information might be provided to any third party for any reason other than as set forth in this Privacy Policy, and you will have an opportunity to request that we not share such information.
Service Providers. We may provide access to your information to select third parties who perform services on our behalf. These third parties provide a variety of services to us including without limitation billing, sales, marketing, advertising, market research, fulfillment, data storage, analysis and processing, identity verification, fraud and safety protection and legal services. As we retain new service providers, we generally seek contractual assurances from these service providers that they will not use your information in any manner other than to help us provide you with the services and products available from Dubarah.
Legal Requirements. We may disclose your information when required by law or when we believe in good faith that such disclosure is necessary to: (a) comply with subpoenas, court orders, or other legal process we receive; (b) establish or exercise our legal rights including enforcing and administering agreements with users; or (c)defend Dubarah against legal claims.If we are required by law to disclose your information, we will use commercially reasonable efforts to notify you unless we believe in our sole discretion that (a) providing notice is prohibited by the legal process itself, court order or applicable law; or (b) we, in our sole discretion, believe that providing notice could create a risk of injury or death, or that harm or fraud could be directed to Dubarah or users. We will attempt to provide the notice by email if you have given us an email address. If you do not challenge the disclosure request, we may be legally required to turn over your information.
Protection of Dubarah and Others. We may disclose your information when we believe it appropriate to investigate, prevent, or take action regarding possible illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of the Terms of Use or any other legal terms governing use of the Platform, and/or to protect our rights and property and the rights and property of other users.
Business Transfers. As we continue to develop our business, we may sell, buy, merge or partner with other companies or businesses, or sell some or all of our assets. In such transactions or where there is any change of control of Dubarah, user information may be among the transferred assets.
App Store Providers. We may provide your identity and mobile device identifier to third-party app store providers (for example, the Apple App Store) to allow you to download our mobile apps.
Please be advised that some information you provide will be publicly accessible. For instance, registration for an Account requires that you provide us with your name. If you register through Facebook, the Platform will use the name associated with your Facebook account. Your name (full name, or in some instances, your first name and last initial) may be visible to other users. Depending on the circumstances, your name may be attached to your Content or information, such as scheduling of Services, service requests, reviews, participating in discussions or forums, messaging, and profile information. Certain other people, including other users with whom you have interacted via the Platform, will see information about you that is attached to your name. For example but without limitation, if you are a Client Member seeking Services, the description you provide of your desired services will be shown to some Dubarah’s registered in the relevant category along with your name. Thus, other users may be able to personally identify you based on Content you provide.
We invite you to post Content on or through our Platform, including your comments, feedback, pictures, and any other information. However, please be careful and responsible whenever you are online. If you choose to post User Content on or through the Platform, such as through Member-to-Member messaging, through our review boards, forums, blogs, or other postings, that information: (a) may be or become publicly available; (b) may be collected and used by third parties without our knowledge; and (c) may be used in a manner that may violate this Policy, the law, or your personal privacy.
5) ONLINE ANALYTICS AND TAILORED ADVERTISING
Analytics
We may use third-party web analytics services on the Platform, such as those of Google Analytics. These service providers use the sort of technology described in the Information That Is Passively or Automatically Collected section above to help us analyze how users use the Platform, including by noting the third-party website from which you arrive. The information collected by the technology will be disclosed to or collected directly by these service providers, who use the information to evaluate your use of the Platform. We also use Google Analytics for certain purposes related to advertising, as described in the following section. To prevent Google Analytics from using your information for analytics, you may install the Google Analytics Opt-Out Browser Add-on.
Tailored Advertising
Third parties whose products or services are accessible or marketed via the Platform may also place cookies or other tracking technologies on your computer, mobile phone, or other device to collect information about your use of the Platform in order to (a) inform, optimize, and serve marketing content based on past visits to our websites and other sites and (b) report how our marketing content impressions, other uses of marketing services, and interactions with these marketing impressions and marketing services are related to visits to our websites. We also allow other third parties(e.g., ad networks and ad servers such as Crashlytics, Facebook and others) to serve tailored marketing to you and to access their own cookies or other tracking technologies on your computer, mobile phone, or other device you use to access the Platform. 
We neither have access to, nor does this Policy govern, the use of cookies or other tracking technologies that may be placed on your computer, mobile phone, or other device you use to access the Platform by non-affiliated, third-party ad technology, ad servers, ad networks or any other non-affiliated third parties. Those parties that use these technologies may offer you a way to opt out of targeted advertising as described below. You may receive tailored advertising on your computer through a web browser. Cookies may be associated with de-identified data linked to or derived from data you voluntarily have submitted to us (e.g., your email address) that we may share with a service provider in hashed, non-human readable form.
If you are interested in more information about tailored browser advertising and how you can generally control cookies from being put on your computer to deliver tailored marketing, you may visit the Digital Advertising Alliance of Canada Opt-Out Tool  to opt-out of receiving tailored advertising from companies that participate in those programs. Please note that to the extent advertising technology is integrated into the Platform, you may still receive advertising content even if you opt out of tailored advertising. In that case, the advertising content will just not be tailored to your interests. Also, we do not control any of the above opt-out links and are not responsible for any choices you make using these mechanisms or the continued availability or accuracy of these mechanisms. If your browsers are configured to reject cookies when you visit this opt-out page, or you subsequently erase your cookies, use a different computer or change web browsers, your opt-out may no longer be effective. Additional information is available on the DAAC's website accessible by the above link.
When using a mobile application you may also receive tailored in-application advertising content. Each operating system, iOS for Apple devices, Android for Android devices and Windows for Microsoft devices, provides its own instructions on how to prevent the delivery of tailored in-application marketing content. You may review the support materials and/or the privacy settings for the respective operating systems in order to opt-out of tailored in-application advertising. For any other devices and/or operating systems, please visit the privacy settings for the applicable device or contact the applicable platform operator.
6) SECURITY
We are committed to ensuring the security of personal information we receive from you, in order to protect it from unauthorized access, collection, use, disclosure, copying, modification, or disposal or similar risks.
We employ appropriate physical, procedural and technological security measures, which are reasonably designed to help protect your personal information from unauthorized access or disclosure. Dubarah may use encryption, passwords, and physical security measures to help protect your personal information against unauthorized access and disclosure. 
Disclaimer to Security. By consenting to the Terms and Conditions of the Site and hence the Privacy Policy, you acknowledge that no data transmission over the Internet is completely secure. We cannot guarantee or warrant the security of any information you provide to us and please be aware that you transmit such information to us at your own risk.
You should take steps to protect against unauthorized access to your password, phone, and computer by, among other things, signing off after using a shared computer, choosing a robust password that nobody else knows or can easily guess, keeping your log-in and password private, and not recycling passwords from other websites or accounts. Dubarah is not responsible for the unauthorized use of your information nor for any lost, stolen, compromised passwords, or for any activity on your Account via unauthorized password activity.
7) LINKS TO EXTERNAL PLATFORMS
The Platform may contain links to other websites or resources over which Dubarah does not have any control. Such links do not constitute an endorsement by Dubarah of those external websites. You acknowledge that Dubarah is providing these links to you only as a convenience, and further agree that Dubarah is not responsible for the content of such external websites or the protection and privacy of information you provide while visiting such external websites.
8) UPDATING, DELETING, AND CORRECTING YOUR INFORMATION
You may review, correct and delete certain information about you by logging into the Platform and navigating to your preferences page in Your profile. You must promptly update your Account information if it changes or is inaccurate. Upon your request, we will close your Account and remove your profile information from view as soon as reasonably possible. We may retain information from closed Accounts in order to comply with the law, prevent fraud, collect any fees owed, resolve disputes, troubleshoot problems, assist with any investigations of any user, enforce our Terms of Use, and/or for any other purposes otherwise permitted by law that we deem necessary in our sole discretion. You should understand, however, that once you transmit User Content through the Platform, you may not be able to change or remove it. Once we have deleted or removed your Account, you agree that Dubarah will not be responsible to you for retaining information related to your Account.
9) YOUR CHOICES REGARDING EMAIL COMMUNICATIONS
We may send periodic promotional or informational emails to you. You may opt out of such communications by following the opt-out instructions contained in the email. Please note that it may take up to 10 business days for us to process opt-out requests. If you opt out of receiving emails about recommendations or other information we think may interest you, we may still send you emails about your Account or any services you have requested or received from us.
10) CHANGES TO THIS POLICY
THIS POLICY IS CURRENT AS OF THE EFFECTIVE DATE SET FORTH ABOVE. Dubarah MAY, IN ITS SOLE AND ABSOLUTE DISCRETION, CHANGE THIS POLICY AT ANY TIME. Dubarah WILL POST ITS UPDATED POLICY ON THE PLATFORM OR SEND YOU AN EMAIL / POP UP WINDOW IN ADVANCE OF THE NEW EFFECTIVE DATE AND DIRECT YOU TO A LINK OF THE UPDATED POLICY. Dubarah ENCOURAGES YOU TO REVIEW THIS POLICY REGULARLY FOR ANY CHANGES. YOUR CONTINUED ACCESS TO OR USE OF THE PLATFORM WILL BE SUBJECT TO THE TERMS OF THE THEN-CURRENT POLICY.
11) CHILDREN'S PRIVACY
Our Services are not designed for children under 18. Only persons 18 years of age or older may use the Platform. If we discover that an individual under 18 has provided us with personal information, we will close the account and delete such information.
12) CONSENT TO TRANSFER
Our computer systems are currently based in Canada, so your personal data will be processed by us in Canada, where data protection and privacy regulations may not offer the same level of protection as in other parts of the world, such as the European Union. If you create an Account with the Platform as a visitor from outside Canada, by using the Platform, you agree to this Policy and you consent to the transfer of all such information to Canada, which may not offer an equivalent level of protection of that required in the European Union or certain other countries, and to the processing of that information as described in this Policy.
13) REFERRALS 
You may choose to invite Members or support staff to join Dubarah by sending invitation emails via our invite feature. Dubarah may store the email addresses you provide so that the respondents may be added to your account, to confirm orders/purchases and also to send reminders of the invitations. 
Dubarah does not sell these email addresses or use them to send any other communication besides invitations and invitation reminders. Recipients of invitations may contact Dubarah to request removal of their information from our database.
CONTACT US
If you have any questions about the Privacy Policy or the Platform, please contact us by sending an email to website@dubarah.com.
";
$lang['jobs'] = 'الوظائف';
$lang['termsofuse'] 			=  'شروط الأستخدام';
$lang['terms'] 					=  "© Dubarah
Terms of Use
Last Updated: Feb 22nd, 2017
IMPORTANT NOTICE: THIS AGREEMENT CONTAINS A BINDING ARBITRATION PROVISION AND CLASS ACTION WAIVER. IT AFFECTS YOUR LEGAL RIGHTS AS DETAILED IN THE ARBITRATION AND CLASS ACTION WAIVER SECTION BELOW. PLEASE READ CAREFULLY.
ACCEPTANCE OF THESE TERMS
This Terms of Use Agreement (Terms), including the BINDING ARBITRATION AND CLASS ACTION WAIVER CONTAINED HEREIN govern your access to, use of, and participation in the Platform made available through the following website: www.Dubarah.com (Dubarah, we, our, or us), including Pro Services obtained from or provided to other users. PLEASE READ THE TERMS THOROUGHLY AND CAREFULLY. BY USING THE PLATFORM, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THE TERMS, THEN YOU MAY NOT ACCESS OR USE THE PLATFORM.
All references to you or your, as applicable, mean the person who accesses, uses, and/or participates in the Platform in any manner, and each of your heirs, assigns, and successors. If you use the Platform on behalf of an entity, you represent and warrant that you have the authority to bind that entity, your acceptance of the Terms will be deemed an acceptance by that entity, and you and your herein shall refer to that entity.
MODIFICATIONS
Dubarah reserves the right, in its sole discretion, to modify these Terms, and any other documents incorporated by reference herein, at any time and without prior notice. Dubarah will notify you of changes by posting on the Platform or sending you an email. Amendments will become effective thirty (30) days after they are posted on the Platform or sent to you by email. Your use of the Platform after the expiration of the thirty (30) days shall constitute your consent to the changes. If you do not agree, you may not access or use the Platform.
ADDITIONAL TERMS AND POLICIES
Please review Dubarah's Privacy Policy, incorporated herein by reference, for information and notices concerning Dubarah's collection and use of your information. Certain areas of and/or products on the Platform may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions or policies. If there is a conflict between these Terms and terms and conditions or policies posted for a specific area or product, the latter take precedence with respect to your use of that area or product.
KEY TERMS
Platform means all Dubarah websites, mobile or other applications, software, processes and any other services provided by or through Dubarah.
Member means a person who completes Dubarah's account registration process or a person who submits or receives a request through Dubarah, including but not limited to Dubarahs and Clients.
Client or Service Recipient means a Member who is registered to search and get hired, receive quotes for services, requests quotes for services, or otherwise uses the Platform to receive, pay for, or facilitate the receipt of services.
“Service Provider(s)” or “Service Member(s)” means a Member who is registered to post services, sends quotes for services, or otherwise uses the Platform to provide, receive payment for, or facilitate the provision of services.
“Dubarah” is the application called such, and/or for which this Terms of Use apply, which is available on the following web address: www.Dubarah.com
Content means text, graphics, images, music, software, audio, video, information or other materials, including but not limited to profile information, services requests, quotes, message threads, reviews, scheduling and calendar information, and other information or materials available on or through the Platform.
Dubarah Content means all Content Dubarah makes available on or through the Platform, including any Content licensed from a third party, but excluding User Content.
User Content means all Content you submit, post, upload, publish, or transmit on or through the Platform, including but not limited to photographs, voice messages, profile information, descriptions, postings, and reviews.
Collective Content means User Content and Dubarah Content together.
Pro Services means the services listed, quoted, scheduled, offered or provided by Service Members, or sought, scheduled or received by Customer Members, through the Platform.
ELIGIBILITY; SERVICE MEMBER REPRESENTATIONS AND WARRANTIES
Access to and use of the Platform is available only to individuals who are at least 18 years old and can form legally binding contracts under applicable law. By accessing or using the Platform, you represent and warrant that you are eligible.
By registering or using the Platform to offer, post or provide services, Dubarahs represent and warrant that they, and the employees, agents, contractors, and subcontractors who may perform work for them, are properly and fully qualified and experienced, and licensed, certified, bonded, and insured, as required by applicable laws or regulations to which they may be subject in the jurisdiction(s) in which they offer their Services and in relation to the specific job they are performing. Dubarahs understand and agree that sending a quote or job application does not guarantee will be read, and using the Platform does not guarantee they will be hired for work or to benefit from the service they apply for.
ACCOUNT REGISTRATION AND OTHER SUBMISSIONS
Users may access the Platform without registering for an account. To access and participate in certain features of the Platform, you will need to create a password-protected account (Account). You may register for an Account using your existing Facebook, Google+, Twitter or LinkedIn account and log-in credentials (your Third-Party Site Password). You agree to provide accurate, current, and complete information during the registration or request submission process and at all other times when you use the Platform, and to update information to keep it accurate, current, and complete. You are solely responsible for safeguarding your Dubarah password and, if applicable, your Third-Party Site Password. You are solely responsible for all activity that occurs on your Account, and you will notify Dubarah immediately of any unauthorized use. Dubarah is not liable for any losses by any party caused by an unauthorized use of your Account. Notwithstanding the foregoing, you may be liable for the losses of Dubarah or others due to such unauthorized use.
YOUR LICENSE TO USE THE PLATFORM
Subject to your compliance with these Terms, Dubarah grants you a limited, non-exclusive, revocable, nontransferable, and non-sublicensable license to reproduce and display Collective Content (excluding any software source code) solely for your personal and non-commercial use and only in connection with your access to and participation in the Platform. You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Platform or Collective Content, except as expressly permitted in these Terms. The Platform and Collective Content are provided to you AS IS. If you download or print a copy of Collective Content for personal use, you must retain all copyright and other proprietary notices contained thereon. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Dubarah or its licensors, except for the licenses and rights expressly granted in these Terms.
USER CONTENT
We may, in our sole discretion, permit you to post, upload, publish, submit or transmit User Content. By making available any User Content on or through the Platform, you hereby grant to Dubarah a worldwide, irrevocable, perpetual, non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, access, view, and otherwise exploit such User Content on, through, by means of or to promote, market or advertise the Platform or Services, or for any other purpose in our sole discretion, except that private messaging through the Platform will not be used by Dubarah in public advertising. In the interest of clarity, the license granted to Dubarah shall survive termination of the Platform or your Account. With the exception of Feedback, Dubarah does not claim ownership rights in your User Content and nothing in these Terms will be deemed to restrict rights that you may have to use and exploit any such User Content.
You acknowledge and agree that you are solely responsible for all User Content that you make available on or through the Platform. Accordingly, you represent and warrant that: (a) you either are the sole and exclusive owner of all User Content that you make available on or through the Platform or you have all rights, licenses, consents and releases that are necessary to grant to Dubarah the rights in such User Content, as contemplated under these Terms; and (b) neither the User Content nor your posting, uploading, publication, submission or transmittal of the User Content or Dubarah's use of the User Content (or any portion thereof) on, through or by means of the Platform will infringe, misappropriate or violate a third party's patent, copyright, trademark, trade secret, moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation. You agree that Dubarah may proofread, summarize or otherwise edit and/or withdraw Content provided by you, and you understand it remains your sole responsibility to monitor your User Content and ensure that such edited Content is accurate and consistent with your representations and warranties in these Terms. You further agree that you are the author of all Content you create and submit to the Platform and that you are the owner of such Content, subject to the license rights granted in these Terms.
Dubarah reserves the right, at any time and without prior notice, to remove or disable access to User Content that we, in our sole discretion, consider to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Platform or users, or for any other reason.
PROHIBITIONS
As a user of the Platform, you may not:
Use another person's Account, misrepresent yourself or Services offered through the Platform, misrepresent your identity or qualifications, misrepresent a project or other information in a quote request, or post Content in any inappropriate category or areas on the Platform;
Use any automated system including but not limited to robots, spiders, offline readers, scrapers to access the Platform for any purpose without Dubarah's prior written approval;
In any manual or automated manner copy copyrighted text, or otherwise misuse or misappropriate Platform information or Content including but not limited to, use on a mirrored, competitive, or third-party site;
Transmit more request messages through the Platform in a given period of time than a human can reasonably produce in the same period by using a conventional online web browser; provided, however, that the operators of public search engines may use spiders or robots to copy materials from the Platform for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such material. Dubarah reserves the right to revoke these exceptions either generally or in specific cases;
Take any action that (a) may unreasonably encumber the Platform's infrastructure; (b) interferes or attempts to interfere with the proper working of the Platform or any third-party participation; (c) bypasses measures that are used to prevent or restrict access to the Platform; (d) circumvents, disables or otherwise interferes with security features of the Platform; (e) distributes viruses or any other technologies that may harm Dubarah or users; (f) uses the Platform in a way that violates any copyrights, trade secrets, or other rights of any third party, including privacy or publicity rights; or (g) circumvents or manipulates Fee (defined herein) structure, billing, or Fees owed;
Collect, harvest or publish any personally identifiable data including but not limited to names or other account information, from the Platform, or use the communication systems provided by the Platform for any reason not explicitly authorized by these Terms, including commercial solicitation purposes;
Recruit, solicit, or contact in any form Service Members or Customer Members for employment or any other use not specifically intended by the Platform;
Take any inappropriate or unlawful actions, including the submission of inappropriate or unlawful Content to or through the Platform, including Content that is harassing, hateful, illegal, profane, obscene, defamatory, threatening, or discriminatory; advocates, promotes, or encourages inappropriate activity, conduct that would be considered a criminal offense, or conduct that would give rise to civil liability or violate any law;
Advertise or solicit a Service not related to or appropriate for the Platform including, but not limited to any Service that (a) is not in supported categories or provides only products; (b) provides directories; (c) offers lending; (d) offers rental space; (e) promotes events (such as a party or professional convention); (f) competes with the business of Dubarah; (g) promotes or offers Ponzi schemes, junk mail, spam, chain letters, pyramid schemes, affiliate marketing or unsolicited commercial content, discount cards, credit counseling, online surveys or contests, raffles, prizes, bonuses, games of chance or giveaways; (h) illegal activity including pornography, sex-trafficking, drugs, arms, terrorism and any other similar activities in similar categories that the law considers a crime.
Submit User Content that damages the experience of any user including but not limited to (a) requests to download non-Dubarah mobile applications and/or links that direct the user to mirrored websites where the user must enter information that is redundant with what has already been entered on Dubarah, (b) offers to purchase a Service or any other service outside of Dubarah, or (c) using a profile page or user name to promote services not offered on or through the Platform;
Take any action that may undermine the efficacy or accuracy of reviews or ratings systems;
Fail to perform Services purchased from you as promised, unless the Client Member fails to materially meet the terms of the mutually agreed-upon agreement for the Services or refuses to pay, or a clear typographical error is made, or you cannot authenticate the Client Member's identity;
Engage in fraudulent conduct including but not limited to offering to make money transfers with intent to request a refund of any portion of the payment or soliciting users to mail cash or use other payment methods not specifically approved by Dubarah;
Sign up for, negotiate a price for, use, or otherwise solicit a Service with no intention of following through with your use of or payment for the Service;
Agree to purchase a Service when you do not meet a Service Member's requirements;
Undertake any activity or engage in any conduct that is inconsistent with the business or purpose of the Platform; and
Attempt to indirectly undertake any of the foregoing.
Dubarah FEES AND TAXES
In connection with use of Dubarah's Platform, Dubarah charges certain Fees (Dubarah Fees or Fees). Current Fees related to some service will be shown when accepting these services. Fees for additional products or services will be shown in policies or terms provided to you before you use such products or services. Dubarah may also charge penalty Fees for fraud, misconduct or other violations of these Terms, as determined in our sole discretion. Information about current penalty Fees is available in the policy or support center. You agree to pay all applicable Fees or charges based on the Fee and billing terms then in effect, regardless of whether you have an active Account. Charges shall be made to your credit card, PayPal or other payment method designated at the time you make a purchase or register for a service. If you do not pay on time or if Dubarah cannot charge a credit card, PayPal or other payment method for any reason, Dubarah reserves all rights permissible under law to recover payment and all costs and expenses incurred, including reasonable attorneys' fees, in our pursuit of payment. You explicitly agree that all communication in relation to delinquent accounts or Fees due will be made by electronic mail or by phone. Such communication may be made by Dubarah or by anyone on its behalf, including but not limited to a third party collection agent. If you cancel your Account at any time, you will not receive any refund. If you have a balance due on any account, you agree that Dubarah may charge such unpaid Fees to your credit card or otherwise bill you for such unpaid Fees. You understand and agree that you are solely responsible for determining your own tax reporting requirements in consultation with tax advisers, and that we cannot and do not offer specific tax advice to either Dubarahs or Clients Members. All sales on Dubarah are final and non-refundable.
DISPUTES BETWEEN OR AMONG USERS
Dubarah values and our Clients, and we understand that occasionally disputes may arise between or among them. Our goal is to provide tools to help users resolve such disputes independently. In the rare event a dispute initiated by either a Dubarah or a Client cannot be resolved independently, you agree, at Dubarah's request, to participate with good faith, to the extent you are reasonably able to do so, in a neutral resolution, mediation or arbitration processes conducted by Dubarah or a neutral third party mediator or arbitrator selected by Dubarah. Notwithstanding the foregoing, you acknowledge and agree that Dubarah is under no obligation to become involved in or impose resolution in any dispute between or among users or any third party.
INTELLECTUAL PROPERTY RIGHTS
Dubarah Content is protected by copyright, trademark, and other laws of Canada, the United States, foreign countries, and international conventions. Except as expressly provided in these Terms, Dubarah and its licensors exclusively own all right, title, and interest in and to the Platform and Dubarah Content, including all associated intellectual property rights. All trademarks, service marks, logos, trade names and any other proprietary designations of Dubarah used herein are trademarks or registered trademarks of Dubarah. Any other trademarks, service marks, logos, trade names and any other proprietary designations are the trademarks or registered trademarks of their respective owners.
FEEDBACK
You acknowledge and agree that all feedback, comments, questions and suggestions (Feedback) you provide to Dubarah are the sole and exclusive property of Dubarah. You hereby irrevocably assign to Dubarah and agree to irrevocably assign to Dubarah all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent, copyright, trade secret, moral and other proprietary or intellectual property rights therein, and waive any moral rights you may have. At our request and expense, you will undertake any tasks we may reasonably request to assist us in acquiring, perfecting and maintaining intellectual property rights and other legal protections for the Feedback. Dubarah shall have no obligation concerning the Feedback, including but not limited to no obligation to return any materials or acknowledge receipt of any Feedback. By sending or otherwise transmitting Feedback to Dubarah, you represent and warrant that you have the right to disclose the Feedback and the Feedback does not violate the rights of any other person or entity. This Feedback section shall survive any termination of your Account or the Platform.
COPYRIGHT POLICY
We expect users to respect copyright law. In appropriate circumstances we will terminate the Account of any user who repeatedly infringes or is believed to be repeatedly infringing the rights of copyright holders.
NO ENDORSEMENT
Dubarah does not endorse any Member, user or any Services, and Dubarah is not a party to any agreements between or among users, Members or third parties. No agency, partnership, joint venture, or employment is created as a result of the Terms or any user's or Member's use of any part of the Platform, including but not limited to any scheduling or other services. Neither Dubarah nor any Members or users of the Platform may direct or control the day-to-day activities of the other, or create or assume any obligation on behalf of the other. Members are required by these Terms to provide accurate information, and although Dubarah may undertake additional checks and processes designed to help verify or check the identities or backgrounds of users, we do not make any representations about, confirm, or endorse any user or their purported identity or background, regardless of the specific Dubarah services they are using or any involvement by Dubarah personnel in providing or scheduling those services.
Any reference on the Platform to a user being licensed or credentialed in some manner, or “Dubarah score”, “Dubarah badge” (or similar language) designations indicates only that the user has completed a relevant account process or met user review standards, and does not represent anything else. Any such description is not an endorsement, certification or guarantee by Dubarah and is not verification of their identity and whether they or their Services are licensed, insured, trustworthy, safe or suitable. Instead, any such description is intended to be useful information for you to evaluate when you make your own decisions about the identity and suitability of others whom you contact or interact with via the Platform. You should always exercise responsibility, due diligence and care when deciding whether to have any interaction with any other user. Dubarah is not responsible for any damage or harm resulting from your interactions with other users.
The Collective Content may contain links to third-party websites, offers, or other events/activities not owned or controlled by Dubarah. We do not endorse or assume any responsibility for any such links, and if you access them, you do so at your own risk.
By using the Platform, you understand and agree that any legal remedy or liability that you seek to obtain for actions or omissions of other users or other third parties will be limited to a claim against those particular users or other third parties. You agree not to attempt to impose liability on or seek any legal remedy from Dubarah with respect to such actions or omissions.
SANCTIONS FOR VIOLATIONS OF THESE TERMS
Without limiting any other rights reserved herein, Dubarah may, in its sole discretion, take any action permitted by law for any violation of these Terms or any other policy or agreement between you and Dubarah, including but not limited to removing User Content you posted, limiting your Account access, requiring you to forfeit certain funds or paid Fees, assessing monetary penalties, terminating your Account, decreasing your status or search rank, canceling quotes or postings, blocking access, investigating you, and/or cooperating with law enforcement agencies in investigation or prosecution.
ACCOUNT SUSPENSION OR TERMINATION
We may, in our discretion, with or without cause, with or without prior notice and at any time, decide to limit, block, suspend, deactivate or cancel your Dubarah Account in whole or in part. If we exercise our discretion under these Terms to do so, any or all of the following can occur with or without prior notice or explanation to you: (a) your Account will be deactivated or suspended, your password will be disabled, and you will not be able to access the Platform or your User Content, or receive assistance from Dubarah support teams; (b) if appropriate in our sole discretion, we may communicate to other users that your Account has been terminated, and why it has been terminated; and (c) you will not be entitled to any compensation for Platform services or Services cancelled or delayed or as a result of Account termination. 
You may cancel your use of the Platform and/or terminate your Account at any time by following the Settings link in in your profile, clicking Profile, and clicking Delete my Account. Please note that if your Account is cancelled, we do not have an obligation to delete or return to you any Content you have posted to the Platform, including, but not limited to, any reviews.
ARBITRATION AND CLASS ACTION WAIVER
PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.
You and Dubarah agree that the Ontario Arbitration Act, 1991, S.O. 1991, c. 17 governs the interpretation and enforcement of these arbitration provisions.
This Section is intended to be interpreted broadly and governs any and all disputes between us including but not limited to claims arising out of or relating to any aspect of the relationship between us, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory; claims that arose before this Agreement or any prior agreement (including, but not limited to, claims related to advertising); and claims that may arise after the termination of this Agreement. The only disputes excluded from this broad prohibition are the litigation of certain intellectual property and small court claims, as provided below.
By agreeing to these Terms, you agree to resolve any and all disputes with Dubarah as follows:
Initial Dispute Resolution: Most disputes can be resolved without resort to litigation. You can reach Dubarah's support department at support@Dubarah.com. The parties agree to use their best efforts to settle any dispute, claim, question, or disagreement directly through consultation with the Dubarah support department, and good faith negotiations shall be a condition to either party initiating a lawsuit or arbitration.
Binding Arbitration: If the parties do not reach an agreed-upon solution within a period of thirty (30) days from the time informal dispute resolution is initiated under the Initial Dispute Resolution provision above, then either party may initiate binding arbitration as the sole means to resolve claims, subject to the terms set forth below. Specifically, all claims arising out of or relating to these Terms (including the Terms' or Privacy Policy's formation, performance, and breach), the parties' relationship with each other, and/or your use of the Platform shall be finally settled by binding arbitration.
Class Action Waiver: The parties further agree that the arbitration shall be conducted in their individual capacities only and not as a class action or other representative action, and the parties expressly waive their right to file a class action or seek relief on a class basis. YOU AND Dubarah AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. If any court or arbitrator determines that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provisions set forth above shall be deemed null and void in their entirety and the parties shall be deemed to have not agreed to arbitrate disputes.
Exception: Litigation of Intellectual Property and Small Claims Court Claims: Notwithstanding the parties' decision to resolve all disputes through arbitration, either party may bring enforcement actions, validity determinations or claims arising from or relating to theft, piracy or unauthorized use of intellectual property in province or federal court or in the Canadian Intellectual Property Office to protect its intellectual property rights (intellectual property rights means patents, copyrights, moral rights, trademarks, and trade secrets, but not privacy or publicity rights). Either party may also seek relief in a small claims court for disputes or claims within the scope of that court's jurisdiction.
30-Day Right to Opt Out: You have the right to opt out and not be bound by the arbitration and class action waiver provisions set forth above by sending (from the email address you use on Dubarah) written notice of your decision to opt out to support@Dubarah.com with the subject line, ARBITRATION AND CLASS ACTION WAIVER OPT-OUT. The notice must be sent within thirty (30) days of your first use of the Platform, otherwise you shall be bound to arbitrate disputes in accordance with the terms of those paragraphs. If you opt out of these arbitration provisions, Dubarah also will not be bound by them.
Changes to This Section: Dubarah will provide thirty (30) days' notice of any changes to this section by posting on the Platform or sending you an email. Amendments will become effective thirty (30) days after they are posted on Dubarah.com or sent to you by email. Changes will apply prospectively only to claims arising after the thirtieth (30th) day. If a court or arbitrator decides that this subsection on Changes to This Section is not enforceable or valid, then this subsection shall be severed from the section entitled Arbitration and Class Action Waiver, and the court or arbitrator shall apply the first Arbitration and Class Action Waiver section in existence after you began using the Platform.
Survival: This Arbitration and Class Action Waiver section shall survive any termination of your Account or the Platform.
GOVERNING LAW
The Terms and the relationship between you and Dubarah shall be governed in all respects by the laws of the province of Ontario, without regard to its conflict of law provisions. You agree that any claim or dispute you may have against Dubarah that is not subject to arbitration must be resolved by a court located in Toronto, Ontario, or a Federal Court located in Toronto, except as otherwise agreed by the parties. You agree to submit to the personal jurisdiction of the courts located within Toronto, Ontario or the a Federal Court located in Toronto, for the purpose of litigating all such claims or disputes that are not subject to arbitration. You hereby waive any and all jurisdictional and venue defenses otherwise available.
DISCLAIMERS
YOUR USE OF THE PLATFORM, PRO SERVICES OR COLLECTIVE CONTENT SHALL BE SOLELY AT YOUR OWN RISK. YOU ACKNOWLEDGE AND AGREE THAT Dubarah DOES NOT HAVE AN OBLIGATION, BUT RESERVES THE RIGHT FOR ANY REASON, TO (A) MONITOR OR REVIEW USER CONTENT; OR (B) CONDUCT IDENTITY VERIFICATION, BACKGROUND OR REGISTERED SEX OFFENDER CHECKS ON ANY MEMBER, INCLUDING BUT NOT LIMITED TO SERVICE MEMBERS AND CUSTOMER MEMBERS. THE PLATFORM IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, Dubarah AND ITS AFFILIATES AND SUBSIDIARIES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES AND AGENTS EXPLICITLY DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT; ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF OR IN TRADE; ANY WARRANTIES, REPRESENTATIONS, OR GUARANTEES IN CONNECTION WITH THIS PLATFORM OR THE PRO SERVICES OFFERED ON OR THROUGH THIS PLATFORM; AND ANY WARRANTIES RELATING TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY OR COMPLETENESS OF ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THIS PLATFORM, INCLUDING WITHOUT LIMITATION ALL COLLECTIVE CONTENT. Dubarah MAKES NO WARRANTY THAT THE PLATFORM OR PRO SERVICES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. Dubarah ASSUMES NO RESPONSIBILITY, AND SHALL NOT BE LIABLE FOR ANY DAMAGES TO YOUR COMPUTER EQUIPMENT OR OTHER PROPERTY ON ACCOUNT OF YOUR ACCESS TO OR USE OF THE PLATFORM. Dubarah SHALL NOT BE LIABLE FOR ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY, OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY DATA, INFORMATION, MATERIALS, SUBSTANCE, OR COLLECTIVE CONTENT POSTED, TRANSMITTED, OR MADE AVAILABLE VIA THE PLATFORM. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM Dubarah OR THROUGH THE PLATFORM, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.
YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OR MEMBERS OF THE PLATFORM AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE PLATFORM, INCLUDING BUT NOT LIMITED TO ANY CUSTOMER MEMBERS, SERVICE MEMBERS OR SERVICE RECIPIENTS. YOU UNDERSTAND THAT Dubarah DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE PLATFORM OR TO REVIEW OR VET ANY PRO SERVICES. Dubarah MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE PLATFORM OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE PLATFORM. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE PLATFORM AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE PLATFORM, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON AND GIVE OR RECEIVE PRO SERVICES. Dubarah EXPLICITLY DISCLAIMS ALL LIABILITY FOR ANY ACT OR OMISSION OF ANY USERS OR THIRD PARTIES.
LIMITATION OF LIABILITY
YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR ACCESS TO AND USE OF THE PLATFORM AND COLLECTIVE CONTENT, YOUR OFFERING OR PROVIDING PRO SERVICES OR REQUESTING OR RECEIVING PRO SERVICES THROUGH THE PLATFORM, AND ANY CONTACT YOU HAVE WITH OTHER USERS OF Dubarah OR THIRD PARTIES, WHETHER IN PERSON OR ONLINE, REMAINS WITH YOU. NEITHER Dubarah NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE PLATFORM WILL BE LIABLE (WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT Dubarah HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE) FOR: (A) ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR LOSS OF GOODWILL; (B) SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE; (C) THE COST OF SUBSTITUTE PRODUCTS OR SERVICES; (D) ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH THESE TERMS; (E) THE USE OF OR INABILITY TO USE THE PLATFORM, PRO SERVICES OR COLLECTIVE CONTENT; (F) ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF THE PLATFORM OR OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE PLATFORM; OR (G) YOUR OFFERING OR PROVIDING PRO SERVICES OR REQUESTING OR RECEIVING PRO SERVICES THROUGH THE PLATFORM.
IN NO EVENT SHALL THE TOTAL, AGGREGATE LIABILITY OF Dubarah AND ITS AFFILIATES AND SUBSIDIARIES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES AND AGENTS, ARISING FROM OR RELATING TO THE TERMS, PLATFORM, PRO SERVICES, AND/OR COLLECTIVE CONTENT, OR FROM THE USE OF OR INABILITY TO USE THE PLATFORM OR COLLECTIVE CONTENT OR IN CONNECTION WITH ANY PRO SERVICES OR INTERACTIONS WITH ANY OTHER USERS EXCEED THE TOTAL AMOUNT OF FEES ACTUALLY PAID TO Dubarah BY YOU HEREUNDER, OR ONE HUNDRED US DOLLARS IF NO SUCH PAYMENTS HAVE BEEN MADE, AS APPLICABLE.
INDEMNIFICATION AND RELEASE
You agree to release, defend, indemnify, and hold Dubarah and its affiliates and subsidiaries, and their respective officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including without limitation reasonable legal and accounting fees, arising out of or in any way connected with (a) your access to or use of the Platform or your violation of these Terms; (b) your User Content or the Collective Content; (c) your interaction with any Member or user; and (d) the request or receipt or offer or provision of Services by you, including but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with such Services.
GENERAL
Force Majeure: Other than payment obligations, neither Dubarah nor you shall be liable to the other for any delay or failure in performance under the Terms arising out of a cause beyond its control and without its fault or negligence. Such causes may include but are not limited to fires, floods, earthquakes, strikes, unavailability of necessary utilities, blackouts, acts of God, acts of declared or undeclared war, acts of regulatory agencies, or national disasters.
No Third-Party Beneficiaries: You agree that, except as otherwise expressly provided in these Terms, there shall be no third-party beneficiaries to these Terms.
Contacting You and E-SIGN Consent: You agree that Dubarah may provide you with notices, including those regarding changes to the Terms, by email, regular mail, or postings on the Platform. With your consent, Dubarah or Service Members may also contact you by telephone or through text messages or by email. If you have agreed to receive text messages or telephone calls from Dubarah or Dubarahs, you also consent to the use of an electronic record to document your agreement. You may withdraw your consent to the use of the electronic record by sending an email to info[at]Dubarahapp[dot]com with Revoke Electronic Consent in the subject line. To view and retain a copy of this disclosure or any information regarding your enrollment in this program, you will need (a) a device (such as a computer or mobile phone) with a web browser and Internet access; and (b) either a printer or storage space on such device. For a free paper copy, or to update our records of your contact information, send an email to info[at]Dubarahapp[dot]com with contact information and the address for delivery.
Entire Agreement: These Terms, together with the Privacy Policy and any other legal notices or additional terms and conditions or policies published by Dubarah on the Platform, shall constitute the entire agreement between you and Dubarah concerning the Platform or Services obtained through the Platform. Except as explicitly stated herein, if any provision of the Terms is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of the Terms, which shall remain in full force and effect.
Waiver: No waiver of any provision of this these Terms shall be deemed a further or continuing waiver of such term or any other term, and Dubarah's failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.
Statute of Limitations: You agree that regardless of any statute or law to the contrary, any claim arising out of or related to the Platform or the Services offered therein must commence within one (1) year after the cause of action accrues. Otherwise, such cause of action is permanently barred.
Section Headings: The section headings in these Terms are for convenience only and have no legal or contractual effect.
Contact Information: If you have any questions about these Terms or the Platform, please contact us by sending an email to website[at]Dubarahapp[dot]com.
";
$lang['update_user'] = "تحديث";
$lang['need_login'] 	=  'عليك تسجيل الدخول لرؤية محتوى هذه الصفحة';
$lang['verify_complet'] 		= 'تم تفعيل حسابك بنجاح';


$lang['days'] 			=  ' ايام';
$lang['developers'] 			=  'المطورون';
$lang['alihajjow'] = "<h3>علي الحجو</h3> <br/> مطور ويب, ومسؤول أنظمة تشغيل. خلال مسيرته المهنية, وقد أثبت رؤيته في تطوير حلول برمجية فعالة وموثوق بها وسهلة الاستعمال، شغفه تجاه هذا المجال لم يصغر أبدا";

$lang['maherkalash'] = "<h3>ماهر كلش</h3> <br/>  قائد فريق المعلوماتية والبرمجة في دوبارة والمشرف العام على الصيانة. مطوّر ويب شغوف بالتعليم والتكنولوجيا. ";





$lang[''] 			=  '';